App\Poscredit\SMSRU\Domain\Entity\SMS:
  type: entity
  repositoryClass: App\Poscredit\SMSRU\Infrastructure\Repository\SMSRepository
  table: sms
  schema: poscredit
  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator
  fields:
    to:
      type: string
      column: sms_to
      length: 251
    msg:
      type: text
    status:
      type: integer
      column: sms_status
      options:
        default: -1
    smsruId:
      type: string
      length: 16
      nullable: true
    createdAt:
      type: datetimetz_immutable
      options:
        default: CURRENT_TIMESTAMP