App\Poscredit\OTP\Domain\Entity\OTP:
  type: entity
  repositoryClass: App\Poscredit\OTP\Infrastructure\Repository\OTPRepository
  table: otp
  schema: poscredit
  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator
  fields:
    createdAt:
      type: datetimetz_immutable
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
    expiresAt:
      type: datetimetz_immutable
      nullable: false
  embedded:
    phone:
      class: App\Poscredit\Shared\ValueObject\Phone
      columnPrefix: false
    code:
      class: App\Poscredit\OTP\Domain\Entity\Code
      columnPrefix: false