App\Poscredit\OTP\Domain\Entity\OTP:
  type: entity
  repositoryClass: App\Poscredit\OTP\Infrastructure\Repository\OTPRepository
  table: otp
  schema: poscredit
  indexes:
    name_index:
      columns: [ phone ]
  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator
  fields:
    phone:
      type: string
      nullable: false
      length: 11
    code:
      type: string
      nullable: false
      length: 64
    createdAt:
      type: datetimetz_immutable
      nullable: false
    expiresAt:
      type: datetimetz_immutable
      nullable: false